### PR TITLE
fix(types): support stringify and parse without passing settings

### LINKED ISSUE #433: remark-parse TS: Property 'settings' is missing in type 'Parse'
### Problem

Calling `unified().use()` with `remark-parse` raises the following error in TypeScript

> Argument of type 'Parse' is not assignable to parameter of type 'ProcessorSettings<Settings>'.
  Property 'settings' is missing in type 'Parse' but required in type 'ProcessorSettings<Settings>'.

### Packages

```json
"remark-parse": "^7.0.0",
"typescript": "^3.5.3",
"unified": "^8.3.2"
```

### Reproduction

A minimal boilerplate from [`unified` readme](https://www.npmjs.com/package/unified#use)

```ts
import unified from 'unified'
import markdown from 'remark-parse'
import remark2rehype from 'remark-rehype'
import html from 'rehype-stringify'

unified()
  .use(markdown) // <--- This causes an error
  .use(remark2rehype)
  .use(html)
```

### Expected behavior

It should raise no warnings / errors.

### Actual behavior

It raises a warning / error.

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolves #433 
related to https://github.com/unifiedjs/unified/pull/67

### CODE REVIEW

File: packages/remark-stringify/types/index.d.ts [hunk 1]
```diff
@@ -1,22 +1,20 @@
...
     (this: Processor, options?: Partial<RemarkStringifyOptions>): void
   }
 
-  type Compiler = RemarkCompiler
+  interface Compiler extends UnifiedCompiler {
+      visitors: {
+        [key: string]: Visitor
+      }
+    }
+  }
```
Comment (vhf) [inline packages/remark-stringify/types/index.d.ts]: There's one extra `}` here ;)

Comment (ChristianMurphy) [reply packages/remark-stringify/types/index.d.ts]: Whoops, corrected

File: packages/remark-parse/types/test.ts [hunk 2]
```diff
@@ -1,12 +1,12 @@
 import unified = require('unified')
-import * as Unist from 'unist'
 import remarkParse = require('remark-parse')
 
 const parseOptions = {
   gfm: true,
   pedantic: true
 }
 
+unified().use(remarkParse)
```
Comment (ChristianMurphy) [inline packages/remark-parse/types/test.ts]: This test is failing currently,

Initially I thought that the extra `Parser` property on the `Attacher` might be the issue
```ts
interface Parse extends Attacher<[Partial<RemarkParseOptions>]> {
  Parser: Parser
}
```

but the tests in https://github.com/unifiedjs/unified/pull/67 passing seem to indicate otherwise.

Other ideas? :thought_balloon:

File: packages/remark-stringify/types/test.ts [hunk 3]
```diff
@@ -8,6 +8,7 @@ const inferredStringifyOptions = {
   incrementListMarker: false
 }
 
+unified().use(remarkStringify)
```
Comment (ChristianMurphy) [inline packages/remark-stringify/types/test.ts]: This test is currently failing,

Initially I thought that the extra `Compiler` property on the `Attacher` might be the issue
```ts
interface Stringify extends Attacher<[Partial<RemarkStringifyOptions>]> {
  Compiler: Compiler
}
```

but the tests in https://github.com/unifiedjs/unified/pull/67 passing seem to indicate otherwise.

Other ideas? :thought_balloon:

File: packages/remark-parse/types/test.ts (hunk 2 above)
Comment (ChristianMurphy) [reply packages/remark-parse/types/test.ts]: With some more testing it looks like
```ts
// this passes
interface Parse extends Attacher {
  Parser: Parser
}

// this fails
interface Parse extends Attacher<[Partial<RemarkParseOptions>]> {
  Parser: Parser
}

// this fails
interface Parse extends Attacher<[Partial<RemarkParseOptions>]> {}
```

extending a type with a generic is causing the issue

File: packages/remark-stringify/types/test.ts (hunk 3 above)
Comment (ChristianMurphy) [reply packages/remark-stringify/types/test.ts]: same findings as https://github.com/remarkjs/remark/pull/434#discussion_r310361481

File: packages/remark-parse/types/test.ts (hunk 2 above)
Comment (ChristianMurphy) [reply packages/remark-parse/types/test.ts]: Found it, the settings needed to be made optional

```ts
// this passes
interface Parse extends Attacher<[Partial<RemarkParseOptions>?]> {
  Parser: Parser
}
```
